# Generated by Django 5.2.9 on 2026-01-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata_age_userdata_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bangla'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2),
        ),
    ]
