# Generated by Django 5.2.9 on 2026-01-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userdata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
