# Generated by Django 5.2.9 on 2026-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bangla'), ('ta', 'Tamil'), ('te', 'Telugu')], max_length=2, null=True),
        ),
    ]
